name: Run Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        php-versions: [ '7.3', '7.4' ]
        mysql-versions: [ '5.7', '8.0' ]
    name: PHP ${{ matrix.php-versions }} with MySQL ${{ matrix.mysql-versions }}

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_USER: root
          MYSQL_DATABASE: test
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_HOST: 127.0.0.1
        ports:
          [ '3306:3306' ]
        options: --health-cmd "mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 10

    steps:
      - uses: actions/checkout@v2
        name: Check Out Code

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Setup Database
        run: |
          sudo apt update
          sudo apt install -y default-mysql-client
          echo 'ALTER USER \'root\'@\'localhost\' IDENTIFIED WITH mysql_native_password BY \'rootpassword\''
          echo 'CREATE DATABASE IF NOT EXISTS test' | mysql -h 127.0.0.1 -u root -prootpassword
          cp tests/db.yml.example tests/db.yml

      - name: Run test suite
        run: ./vendor/bin/phpunit
